version: "3.8"

services:
  postgres:
    container_name: power-postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
  redis:
    container_name: power-redis
    image: redis:5
    ports:
      - "6379:6379"

